### ISSUE TITLE
Creating a footer

### ISSUE THREAD

**Issue by vinielk** [CodetheChangeFoundation/climatehub#1]
### Acceptance Criteria:
* Three columns with a logo and description, social media icons, and a donate button
* Light grey background (look at mocks)

### Definition of Done:
* Wiki updated

**Comment by melissab1238** [comment]
Todo:
add colors to footer (both green and black rows)
find social media icons and link the FB (for now)
create custom fields for aspects of the grid (except copyright row)
make the font smaller if possible
develop JS script to automatically update year
design grid to look nice on phone too for the first row (logo/intro words, follow us, donate/donate words)

**Comment by melissab1238** [comment]
TD: 

- hover feature on social media icons (remove green and underline)
- remove underline on other links?
- make the footer more compact (less vert space)
- consider design on phones
