### ISSUE TITLE
Asset Map

### ISSUE THREAD

**Issue by vinielk** [CodetheChangeFoundation/climatehub#49]
**Scope:**
- Create an interactive map which can be used to display universities/cities, groups, projects and individuals.

**Acceptance Criteria:**
- On page load, map shows UBC node centred on the map.
- When a university or city node is clicked, the map zooms in and shows all the groups and their projects.
  - A group must be connected, by a line, to their projects.
  - Projects shared between two or more groups should have multiple connecting groups.
- When a group node is clicked, the map shows all the projects and individuals that belong to that group.
- When a project node is clicked, the map will  only show the project and its connected groups.
  - Details about the project are shown in the bottom-right corner.
- There is a legend in the top-right corner of the map which shows your current zoom-level.
- Under the map is a search field with results that changes based on what is clicked in the map.

**Implementation Details:**
- Most likely written in react and injected into a div element on Wordpress.
- Use d3 library to construct nodes and connections between groups, project and individuals.
- Use public API, written in climatehub-api repo

**Comment by sumeetgrewal** [comment]
Completed Asset Map v1.0. Currently in beta testing at [http://test.ubcclimatehub.ca/asset-map/](http://test.ubcclimatehub.ca/asset-map/).

**Comment by sumeetgrewal** [comment]
Asset Map deployed to production site, currently unpublished.
