### ISSUE TITLE
Asset Map Search Form Frontend

### ISSUE THREAD

**Issue by vinielk** [CodetheChangeFoundation/climatehub#53]
Implement the frontend of the search form.

**Acceptance Criteria**
- must be a separate class in react
- must be able to take an array of search results and dynamically display them in the table
- must have dropdown to filter results (in our case "Groups", "Projects" and "Individuals")
  - these should not be hardcoded (need to figure out best way to do this)
- must be styled according to Figma design file

**Out of scope**
- does not need to be optimized for mobile, but should contain responsive bootstrap classes (i.e. col-sm-6 col-lg-12)
- no search logic should be implemented as part of this ticket

**Comment by sumeetgrewal** [comment]
Community/City Multiple Select complete
Post Type dropdown is complete - this is retrieved from categories state
Remaining : 
- Search form
- Post view
- Tag select
- Filters bar
