### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/climatehub#6]
### Acceptance Criteria:
* Create a fixed navigation bar
* As you scroll down, the navigation bar stays fix, but shrinks in size <https://codepen.io/ondrejsvestka/pen/yXJjLj>
* Hovering over an item causes a solid black box to drop down, changing the text colour to white
* Current page has a solid green line at the top instead of a solid black line

### Definition of Done:
* Wiki updated

**Comment by vinielk** [comment]
Done in refactor branch
