### ISSUE TITLE
Update ACF fields

### ISSUE THREAD

**Issue by vinielk** [CodetheChangeFoundation/climatehub#85]
* After data is cached, update all ACF fields
* Test location with Viniel's API key
* Check for errors and write to csv file
  * create field to upload csv file on options page (hidden if no errors)

**Comment by sumeetgrewal** [comment]
Fields are updates and errors are logged. 
Remaining: Errors need to be written to 'Import Status File' for export

**Comment by sumeetgrewal** [comment]
completed in CH-54
